### ISSUE TITLE
Provide small object for top grasps

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-gazebo-grasping-sandbox#13]
In order to showcase top grasps, we would need a second object, smaller (shorter) than the mustard bottle.

A synthetic box with sizes that can be customized could be enough. A plus would be another object from the YCB, but small.

@xEnVrE would you be willing to fork and pull-request the required models?

**Comment by xEnVrE** [comment]
Hi @pattacini,

I can provide both.  For YCB, we can use the potted meat can or the tomato soup in order to add shapes other than the resizable box.

**Comment by pattacini** [comment]
Fantastic @xEnVrE 👍🏻 
Let's go for YCB only then!

**Comment by pattacini** [comment]
@xEnVrE please, add up only the models w/o touching the world yet.
How objects will be handled within the world (using randomization – see #12) needs to be done with a careful eye.
