### ISSUE TITLE
Unable to start up the world in local containers

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-gazebo-grasping-sandbox#24]
## Brief description
We're able to run the docker container locally but not to launch the world in Gazebo.

## Detailed context
In detail, Gazebo is able to start up but not when launched with:
```
$ gazebo -e dart icub-gazebo-grasping-sandbox.sdf
```

I've already checked that all the required files are installed correctly and that the Gazebo related env variables are configured just fine.

**Comment by pattacini** [comment]
@xEnVrE would you be willing to give a look at this?

Actually, after a long wait, something will show up, but in an unexpected way:

![screenshot](https://user-images.githubusercontent.com/3738070/90551729-114daf00-e192-11ea-948f-3f1d04b959aa.png)

ℹ Instructions on how to run the docker image locally are available [here](https://github.com/robotology/icub-gazebo-grasping-sandbox/blob/master/dockerfiles).

**Comment by xEnVrE** [comment]
@pattacini yes I will have a look at this and let you know

**Comment by pattacini** [comment]
Thanks heaps @xEnVrE 👍🏻

**Comment by xEnVrE** [comment]
Hi @pattacini 

I was able to reproduce the issue, i.e. Gazebo is stuck at the splash screen. I tried opening `gazebo` alone and noticed that the models of the table and of the objects are not available in the `Insert` tab. Indeed, by checking the `GAZEBO_MODEL_PATH` I found that it is not pointing to the folder containing such models.

I tried running instead
```
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/workspace/icub-gazebo-grasping-sandbox/gazebo/models
gazebo -e dart icub-gazebo-grasping-sandbox.sdf
```

and that worked 

![gazebo_grasping_local_0](https://user-images.githubusercontent.com/6014499/90617697-4a783480-e20f-11ea-9d6c-7649ac00f0d7.png)

Maybe, we are missing something while exporting env variables. Wondering how is it working on GitPod then.

**Comment by pattacini** [comment]
That's right! We're not exporting that path from the docker: see https://github.com/robotology/icub-gazebo-grasping-sandbox/blob/master/dockerfiles/Dockerfile#L135.

🤔 It's weird how we managed to get it to work in Gitpod then, although I've noticed that Gitpod mixes a bit the env.

Many thanks!

**Comment by pattacini** [comment]
Well, hold on!

Making `GAZEBO_MODEL_PATH` points to `workspace/icub-gazebo-grasping-sandbox/gazebo/models` is wrong, as those models get installed in `${ICUBcontrib_DIR}`. Look at there.

@xEnVrE can you please do a further quick test and extend that env var to include the correct path to `${ICUBcontrib_DIR}/share/...something...`? Models are also located there.

**Comment by xEnVrE** [comment]
That is working @pattacini

**Comment by pattacini** [comment]
@xEnVrE also spotted problems related to the use of the `unix_stream` carrier on the local container.
A fix is underway!

**Comment by pattacini** [comment]
>Wondering how is it working on GitPod then.

@xEnVrE this was the reason why we managed to get it to work on Gitpod earlier: d687637d6662d275e302bfd479e25fd2a41556a2.
