### ISSUE TITLE
Possible bug in CardinalPointsGrasp::getCandidates()

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-gazebo-grasping-sandbox#49]
### Bug description

Looking at the code at lines:

https://github.com/robotology/icub-gazebo-grasping-sandbox/blob/74e09c46c0937b8f4c96b287a0a862f134c5f401/src/cardinal_points_grasp.h#L171-L178

It seems to me that the property `max_iter` gets assigned an additional float value at line `176` due to the line `opt1.addFloat()` and that the property `tol` receives the value that was designed for `constr_tol`. Finally, the property `constr_tol` remains without a value.

Should not the code be instead:

```
 yarp::os::Bottle options; 
 auto& opt1 = options.addList(); 
 opt1.addString("max_iter"); opt1.addInt32(1000); 
 auto& opt2 = options.addList(); 
 opt2.addString("tol"); opt2.addFloat64(.0001); 
 auto& opt3 = options.addList(); 
 opt3.addString("constr_tol"); opt3.addFloat64(.000001); 
```

Or is there a different intepretation for actual code?

Thank you

### Steps to reproduce

This issue is notifying a possible typo within the class `CardinalPointsGrasp`. Hence, this section is not actually required.

**Comment by pattacini** [comment]
Good catch!
I'll open a PR to fix that.
